name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
        xcodebuild -version

    - uses: actions/checkout@v1

    - name: Swift build
      run: |
        swift build
